encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "enc"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.entries, name="entries"),
    path('search', views.search, name='search'),
    path('random', views.random_result, name='random'),
    path('create', views.create_page, name='create'),
    path('edit', views.edit_page, name='edit'),
    path("save",views.save_page, name="save")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
import markdown2
from . import util
import random

entry_list = []
def check_data(str, sub_str):
    if (str.find(sub_str) == -1):
        return 0
    else:
        return 1

def index(request):
    
    entry_list.clear()
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entries(request, name):  
      
    html = util.get_entry(name)
    if html is None:
        error = f'The page {name} was not found'
        return render(request, "encyclopedia/error.html",{
                'name':name,
                'error':error
            })
    html = markdown2.markdown(f"{html}")
    entries = util.list_entries()
    for entry in entries:
        if entry in entries:
            return render(request,"encyclopedia/entry.html",{

                "name":name,
                "content": html

        })
    
    
    
    
def search(request):
     entries = util.list_entries()
     entry_list.clear()
     if request.method == 'POST':    
        q=request.POST['q'].lower()  
        q_html = util.get_entry(q)
        q_html = markdown2.markdown(f"{q_html}")
        for entry in entries:
            entry = entry.lower()
            if entry == q:
                return render(request, "encyclopedia/entry.html",{
                    "name":q,
                    "content":q_html
                }) 
            elif check_data(entry,q) == 1:
                entry_list.append(entry)
            
                
        return render(request,"encyclopedia/search_results.html",{
            'entries' : entry_list
        } )    
                
def random_result(request):
    return entries(request,random.choice(util.list_entries()))


def create_page(request):
    if request.method =='POST':
        title= request.POST['title']
        text_area = request.POST['text_area']
        entry_list = util.list_entries()
        for entry in entry_list:
            if title.lower() == entry.lower():
                error = 'Page already exist with this title'
                return render(request,"encyclopedia/error.html",{
                    'error': error
                })
        util.save_entry(title,text_area)
        return entries(request,title)
   
    else:    
        return render(request,"encyclopedia/create_page.html")

def edit_page(request):
    if request.method == 'POST':
        name = request.POST['name']
        md = util.get_entry(name)

        return render(request, "encyclopedia/edit_page.html",{
            'md':md,
            'name':name
        })

def save_page(request):
    if request.method=='POST':
        md=request.POST['text_area']
        title = request.POST['title']
        util.save_entry(title,md)
        return entries(request,title)

encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create Page
{% endblock %}

{% block body %}
    
    <form action='{% url "enc:create" %}' method='POST'>
        {% csrf_token %}    
        <input type='text' placeholder="Entry Title" name='title'>
        <textarea rows="1" cols="25" name='text_area' style='height: 250px;display: block;margin-top: 15px;'>This section for Markdown entry</textarea>
        <input type='submit' value="Save" style='margin-top: 5px;'>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    
    <form action='{% url "enc:save" %}' method='POST'>
        {% csrf_token %}    
        <input type='hidden' value='{{name}}' name='title'>
        <textarea rows="1" cols="25" name='text_area' style='height: 250px;display: block;margin-top: 15px;'>{{md}}</textarea>
        <input type='submit' value="Save" style='margin-top: 5px;'>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{name|safe}}
{% endblock %}

{% block body %}
    
    {{content|safe}}
    <form action='{% url "enc:edit"%}' method="POST">
        {% csrf_token %}
        <input type='submit' value='Edit Page'>
        <input type='hidden' value="{{name}}" name='name'>
        <input type='hidden' value="{{content}}" name='content'>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    
    <h1 style='text-align: center;'>{{error}}</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href='/wiki/{{entry}}'>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body style='overflow-x:hidden;'>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action='{% url "enc:search" %}' method='POST'>
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form > 
                <div>
                    <a href="{% url 'enc:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'enc:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href='{% url "enc:random" %}' >Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href='/{{entry}}'>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href='/wiki/{{entry}}'>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}